"""fixed foreign key error on CommuteTime

Revision ID: d3030de021f6
Revises: 8a084a1b572d
Create Date: 2024-10-08 16:39:44.314934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3030de021f6'
down_revision = '8a084a1b572d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commute_times', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_commute_times_commute_id_commutes'), 'commutes', ['commute_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commute_times', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_commute_times_commute_id_commutes'), type_='foreignkey')

    # ### end Alembic commands ###
